version: '3.9'


services:
  backend:
    build: './core'
    container_name: "backend"
    restart: "always"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - './core:/app'

    environment:
      - SECRET_KEY='django-insecure-$6ld(_gl^1au5%nf9wni8h1cu%kl555^j+p%l#o(9$^5ou*vh6'
      - DEBUG=True
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - 8000:8000

  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672" 
      - "15672:15672" # Web UI port

  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=root_db