version: '3.9'


services:
  backend:
    build: './core'
    container_name: "backend"
    restart: "always"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - './core:/app'

    environment:
      - SECRET_KEY='django-insecure-$6ld(_gl^1au5%nf9wni8h1cu%kl555^j+p%l#o(9$^5ou*vh6'
      - DEBUG=True
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - 8000:8000

  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    restart: "always"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672" 
      - "15672:15672" # Web UI port

  postgres:
    image: postgres:14-alpine
    container_name: postgres
    restart: "always"
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=root_db
  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      # Change the number before : to the port the web interface should be accessible on
      - '5000:80'
      # Change the number before : to the port the SMTP server should be accessible on
      - '25:25'
      # Change the number before : to the port the IMAP server should be accessible on
      - '143:143'
    volumes:
      # This is where smtp4dev stores the database..
        - smtp4dev-data:/smtp4dev
    environment:
      
      - ServerOptions__HostName=smtp4dev

     

volumes:
  smtp4dev-data: