# Generated by Django 4.2.7 on 2023-11-18 18:14

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VarientTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, editable=False, verbose_name="Is Active?"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, verbose_name="UUID"
                    ),
                ),
                ("title", models.CharField(max_length=400, verbose_name="Title")),
                (
                    "varient_type",
                    models.CharField(
                        choices=[("Color", "Color"), ("Select box", "Select Box")],
                        max_length=100,
                        verbose_name="Varient type",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.AddField(
            model_name="category",
            name="meta_description",
            field=models.TextField(
                blank=True,
                help_text="Meta Description",
                max_length=600,
                null=True,
                verbose_name="Meta description",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="meta_keywords",
            field=models.TextField(
                blank=True,
                help_text="Meta Keywords",
                max_length=600,
                null=True,
                verbose_name="Meta keywords",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="Meta Title",
                max_length=400,
                null=True,
                verbose_name="Meta title",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(
                to="product.category", verbose_name="Categories"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="discount",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="Discount"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="discount_type",
            field=models.CharField(
                blank=True,
                choices=[("Percentage", "Percentage"), ("Value", "Value")],
                max_length=70,
                null=True,
                verbose_name="Discount type",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_digital",
            field=models.BooleanField(
                default=False, verbose_name="Is digital product?"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="meta_description",
            field=models.TextField(
                blank=True,
                help_text="Meta Description",
                max_length=600,
                null=True,
                verbose_name="Meta description",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="meta_keywords",
            field=models.TextField(
                blank=True,
                help_text="Meta Keywords",
                max_length=600,
                null=True,
                verbose_name="Meta keywords",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="Meta Title",
                max_length=400,
                null=True,
                verbose_name="Meta title",
            ),
        ),
        migrations.CreateModel(
            name="Varient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, editable=False, verbose_name="Is Active?"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, verbose_name="UUID"
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        blank=True, max_length=400, null=True, verbose_name="Value"
                    ),
                ),
                (
                    "color",
                    colorfield.fields.ColorField(
                        blank=True,
                        default=None,
                        image_field=None,
                        max_length=25,
                        null=True,
                        samples=None,
                        verbose_name="Color",
                    ),
                ),
                (
                    "title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.varienttitle",
                        verbose_name="Varient Title",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
