# Generated by Django 4.2.7 on 2023-11-18 19:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_varienttitle_remove_product_category_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="price",
            new_name="unit_price",
        ),
        migrations.AddField(
            model_name="varient",
            name="color_name",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="Color name"
            ),
        ),
        migrations.CreateModel(
            name="ProductInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, editable=False, verbose_name="Is Active?"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, verbose_name="UUID"
                    ),
                ),
                ("quantity", models.PositiveBigIntegerField(verbose_name="Quantity")),
                ("price", models.PositiveBigIntegerField(verbose_name="Price")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                        verbose_name="Product",
                    ),
                ),
                (
                    "varients",
                    models.ManyToManyField(
                        to="product.varient", verbose_name="Varients"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
