# Generated by Django 4.2.7 on 2023-11-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_rename_price_product_unit_price_varient_color_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discount_type",
            field=models.CharField(
                blank=True,
                choices=[("PERCENTAGE", "Percentage"), ("VALUE", "Value")],
                max_length=70,
                null=True,
                verbose_name="Discount type",
            ),
        ),
        migrations.AlterField(
            model_name="varienttitle",
            name="varient_type",
            field=models.CharField(
                choices=[("COLOR", "Color"), ("SELECT BOX", "Select Box")],
                max_length=100,
                verbose_name="Varient type",
            ),
        ),
    ]
